// dilema-archive maintains a SQLite full-text archive of Dilema Veche articles.
//
// Data flows in from two sources:
//
//	ingest articles.jsonl — weekly output of the TypeScript scraper. Rich
//	                        (carries URLs) and authoritative: on conflict it
//	                        overwrites what an EPUB backfill row provided.
//	backfill *.epub       — EPUBs generated by the scraper in previous weeks.
//	                        Seeds issues from before articles.jsonl existed;
//	                        these rows have no URL until a later ingest fills it.
//
// Articles are deduplicated per (issue, title) — see upsert in db.go.
package main

import (
	"bufio"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"

	"flag"
)

// Article is the shape of one articles.jsonl line — the data contract with
// src/scraper.ts. EPUB backfill parses into the same struct.
type Article struct {
	URL      string `json:"url"`
	Title    string `json:"title"`
	Subtitle string `json:"subtitle"`
	Author   string `json:"author"`
	Section  string `json:"section"`
	Date     string `json:"date"` // YYYY-MM-DD
	Issue    string `json:"issue"`
	Body     string `json:"body"`

	source string // "jsonl" | "epub", set by the command, not the input
}

func usage() {
	fmt.Fprint(os.Stderr, `usage: dilema-archive [-db dilema.db] <command> [args]

commands:
  ingest <articles.jsonl>   upsert the scraper's weekly output
  backfill <epub ...>       seed historical issues from generated EPUBs
  search [-n 10] <query>    FTS5 search (supports AND, OR, NEAR, "phrase")
  stats                     totals per issue, section and author
`)
	os.Exit(2)
}

func main() {
	dbPath := flag.String("db", "dilema.db", "path to the SQLite database")
	flag.Usage = usage
	flag.Parse()
	if flag.NArg() < 1 {
		usage()
	}

	db, err := openDB(*dbPath)
	if err != nil {
		fatal("open %s: %v", *dbPath, err)
	}
	defer db.Close()

	switch cmd, args := flag.Arg(0), flag.Args()[1:]; cmd {
	case "ingest":
		if len(args) != 1 {
			usage()
		}
		cmdIngest(db, args[0])
	case "backfill":
		if len(args) == 0 {
			usage()
		}
		cmdBackfill(db, args)
	case "search":
		cmdSearch(db, args)
	case "stats":
		cmdStats(db)
	default:
		usage()
	}
}

func fatal(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "dilema-archive: "+format+"\n", a...)
	os.Exit(1)
}

func cmdIngest(db *sql.DB, path string) {
	f, err := os.Open(path)
	if err != nil {
		fatal("%v", err)
	}
	defer f.Close()

	var articles []Article
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<24) // article bodies exceed the 64K default line limit
	for line := 1; sc.Scan(); line++ {
		if len(sc.Bytes()) == 0 {
			continue
		}
		var a Article
		if err := json.Unmarshal(sc.Bytes(), &a); err != nil {
			fatal("%s:%d: %v", path, line, err)
		}
		a.source = "jsonl"
		articles = append(articles, a)
	}
	if err := sc.Err(); err != nil {
		fatal("%s: %v", path, err)
	}

	ins, upd := store(db, articles)
	fmt.Printf("%s: %d articles — %d new, %d updated\n", path, len(articles), ins, upd)
}

func cmdBackfill(db *sql.DB, paths []string) {
	totalIns, totalUpd := 0, 0
	for _, path := range paths {
		articles, err := parseEpub(path)
		if err != nil {
			fatal("%s: %v", path, err)
		}
		ins, upd := store(db, articles)
		totalIns += ins
		totalUpd += upd
		fmt.Printf("%s: %d articles — %d new, %d updated\n", path, len(articles), ins, upd)
	}
	if len(paths) > 1 {
		fmt.Printf("total: %d new, %d updated\n", totalIns, totalUpd)
	}
}

func store(db *sql.DB, articles []Article) (inserted, updated int) {
	tx, err := db.Begin()
	if err != nil {
		fatal("%v", err)
	}
	defer tx.Rollback()
	for _, a := range articles {
		isNew, err := upsert(tx, a)
		if err != nil {
			fatal("upsert %q (%s): %v", a.Title, a.Issue, err)
		}
		if isNew {
			inserted++
		} else {
			updated++
		}
	}
	if err := tx.Commit(); err != nil {
		fatal("%v", err)
	}
	return inserted, updated
}

func cmdSearch(db *sql.DB, args []string) {
	fs := flag.NewFlagSet("search", flag.ExitOnError)
	limit := fs.Int("n", 10, "max results")
	fs.Parse(args)
	if fs.NArg() != 1 {
		usage()
	}

	rows, err := db.Query(`
		SELECT a.issue, a.section, a.author, a.title,
		       snippet(articles_fts, 3, '«', '»', ' … ', 14)
		FROM articles_fts
		JOIN articles a ON a.id = articles_fts.rowid
		WHERE articles_fts MATCH ?
		ORDER BY bm25(articles_fts)
		LIMIT ?`, fs.Arg(0), *limit)
	if err != nil {
		fatal("search: %v", err)
	}
	defer rows.Close()

	n := 0
	for rows.Next() {
		var issue, section, author, title, snip string
		if err := rows.Scan(&issue, &section, &author, &title, &snip); err != nil {
			fatal("%v", err)
		}
		n++
		fmt.Printf("%d. [%s] %s — %s (%s)\n   %s\n", n, issue, title, author, section, snip)
	}
	if err := rows.Err(); err != nil {
		fatal("%v", err)
	}
	if n == 0 {
		fmt.Println("no matches")
	}
}

func cmdStats(db *sql.DB) {
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM articles`).Scan(&total); err != nil {
		fatal("%v", err)
	}
	fmt.Printf("%d articles\n\nper issue:\n", total)
	printCounts(db, `SELECT issue, COUNT(*) FROM articles GROUP BY issue ORDER BY issue`)
	fmt.Println("\ntop sections:")
	printCounts(db, `SELECT section, COUNT(*) c FROM articles GROUP BY section ORDER BY c DESC LIMIT 10`)
	fmt.Println("\ntop authors:")
	printCounts(db, `SELECT author, COUNT(*) c FROM articles WHERE author != '' GROUP BY author ORDER BY c DESC LIMIT 10`)
}

func printCounts(db *sql.DB, query string) {
	rows, err := db.Query(query)
	if err != nil {
		fatal("%v", err)
	}
	defer rows.Close()
	for rows.Next() {
		var label string
		var n int
		if err := rows.Scan(&label, &n); err != nil {
			fatal("%v", err)
		}
		fmt.Printf("  %4d  %s\n", n, label)
	}
	if err := rows.Err(); err != nil {
		fatal("%v", err)
	}
}
